### ISSUE TITLE
AttributeError: 'EncodedStreamObject' object has no attribute 'getData'

### ISSUE THREAD

**Issue by Richzendy** [py-pdf/PyPDF2#1138]
I'm have a script to extract attachment from PDF files, everything was working to upgrade pyPDF2 to the last version, i'm getting this error:

`AttributeError: 'EncodedStreamObject' object has no attribute 'getData'`

This is part of my code to extract atrachment from PDF:

``` # Step 1 Read pdf into a variable
    pdf = pf.PdfFileReader(fname)

    # Step 2 "The process of traversing the PDF tree structure"
    catalog = pdf.trailer['/Root']

    fDetail = catalog['/Names']['/EmbeddedFiles']['/Names']

    soup = fDetail[1].getObject()
     # Step 3 Stream data to a variable for further use
    file = soup['/EF']['/F'].getData()
```
## Environment

This error happen with PyPDF2 version 1.28.3 and above, my code works with 1.28.2 version.

I've made rollback to 1.28.2 version to get working everything again.

**Comment by MasterOdin** [comment]
Thanks for reporting. It looks like this bug affects all version 1.28.3+, including 2.0+ releases. I've made PRs targeting both major versions as I feel like this is an easy enough bug to fix to warrant a backport.

**Comment by MartinThoma** [comment]
Thank you both very much! I'll make a release today (PyPDF2==2.6.1 or PyPDF2==2.7.0; I need to check if we added new features).

**Comment by MasterOdin** [comment]
@Richzendy A fix for this has been published in both [1.28.5](https://github.com/py-pdf/PyPDF2/releases/tag/1.28.5) and [2.7.0](https://github.com/py-pdf/PyPDF2/releases/tag/2.7.0).
