### PR TITLE
BUG: Add missing deprecated EncodedStreamObject functions

### LINKED ISSUE #1138: AttributeError: 'EncodedStreamObject' object has no attribute 'getData'
I'm have a script to extract attachment from PDF files, everything was working to upgrade pyPDF2 to the last version, i'm getting this error:

`AttributeError: 'EncodedStreamObject' object has no attribute 'getData'`

This is part of my code to extract atrachment from PDF:

``` # Step 1 Read pdf into a variable
    pdf = pf.PdfFileReader(fname)

    # Step 2 "The process of traversing the PDF tree structure"
    catalog = pdf.trailer['/Root']

    fDetail = catalog['/Names']['/EmbeddedFiles']['/Names']

    soup = fDetail[1].getObject()
     # Step 3 Stream data to a variable for further use
    file = soup['/EF']['/F'].getData()
```
## Environment

This error happen with PyPDF2 version 1.28.3 and above, my code works with 1.28.2 version.

I've made rollback to 1.28.2 version to get working everything again.

### PR DESCRIPTION
**Pull request by MasterOdin**
Closes #1138 

The `EncodedStreamObject` class was missing the deprecated `getData` and `setData` functions, which would call the `get_data` and `set_data` functions respectively after issuing a deprecation warning. The original functions were totally renamed in https://github.com/py-pdf/PyPDF2/commit/c774ab0cbc82c99a7dcbaa3260b6c4545f1b3659. That same commit did properly handle the `getData` and `setData` functions in the `DecodedStreamObject` though, where they issue a deprecation warning and then call `get_data` and `set_data`.

This should probably be backported to 1.x where it exists as well, as it should be simple enough, and the user in #1138 is using 1.28.2 and cannot upgrade due to this bug.

### CODE REVIEW

**Comment by MartinThoma** [comment]
Thank you :hugs: I will make a release today with the fix for the current main branch.

I'm uncertain if I really want to do backports. For which versions would I need to do them? For which kinds of bugs would we make it? How long would we need to support old versions?

**Comment by MasterOdin** [comment]
I think the only thing that should be backported is just these sorts of PRs, where functions were unintentionally broken by a rename or whatever, and that the fix is super straightforward. Given the probably very long tail of 1.x usage that exists and time between major releases, I would say support backporting for like 6 months or so, but I don't imagine there should be _that_ many of these sorts of reports.

Any other changes or features I think should not be backported.

**Comment by MartinThoma** [comment]
Sounds good and also a reasonable workload. Let's do that :-) Thank you :-)
